# Variables
K8SV = '1.33.1-1.1' # Kubernetes Version : apt list -a kubelet , ex) 1.32.5-1.1
CONTAINERDV = '1.7.27-1' # Containerd Version : apt list -a containerd.io , ex) 1.6.33-1
CILIUMV = '1.17.4' # Cilium CNI Version : https://github.com/cilium/cilium/tags
N = 2 # max number of worker nodes

# Base Image  https://portal.cloud.hashicorp.com/vagrant/discover/gutehall/ubuntu24-04
BOX_IMAGE = "bento/ubuntu-24.04"
BOX_VERSION = "202502.21.0"

Vagrant.configure("2") do |config|
#-ControlPlane Node
    config.vm.define "k8s-ctr" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = BOX_VERSION
      subconfig.vm.provider "vmware_fusion" do |vb|
        vb.gui = true
        vb.cpus = 2
        vb.memory = 2560
        vb.linked_clone = false
      end
      subconfig.vm.host_name = "k8s-ctr"
      subconfig.vm.hostname = "k8s-ctr"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      subconfig.vm.network "forwarded_port", guest: 22, host: 50000, auto_correct: true, id: "ssh"
      subconfig.vm.provision "shell", path: "init_cfg.sh", args: [ K8SV, CONTAINERDV]
      subconfig.vm.provision "shell", path: "k8s-ctr.sh", args: CILIUMV
    end

#-Worker Nodes
  (1..N).each do |i|
    config.vm.define "k8s-w#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = BOX_VERSION
      subconfig.vm.provider "vmware_fusion" do |vb|
        vb.gui = true
        vb.cpus = 2
        vb.memory = 1536
        vb.linked_clone = false
      end
      subconfig.vm.host_name = "k8s-w#{i}"
      subconfig.vm.hostname = "k8s-w#{i}"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      subconfig.vm.network "forwarded_port", guest: 22, host: "5000#{i}", auto_correct: true, id: "ssh"
      subconfig.vm.provision "shell", path: "init_cfg.sh", args: [ K8SV, CONTAINERDV]
    end
  end

#-Router Node
    config.vm.define "router" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = BOX_VERSION
      subconfig.vm.provider "vmware_fusion" do |vb|
        vb.gui = true
        vb.cpus = 1
        vb.memory = 512
        vb.linked_clone = false
      end
      subconfig.vm.host_name = "router"
      subconfig.vm.hostname = "router"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      subconfig.vm.network "forwarded_port", guest: 22, host: 50009, auto_correct: true, id: "ssh"
      subconfig.vm.provision "shell", path: "router.sh"
    end

end
